<?php

  return [
    'ROLEADMIN' => '1',
    'ROLEBUSSINESS' => '2',
    'ROLEUSER' => '3',
    'ROLE_ADMIN' => 'Admin',
    'ROLE_BUSINESS' => 'Business',
    'ROLE_USER' => 'User',
    'MIN_POINT' => '0',
    'MAX_POINT' => '10',
    'STEP_POINT' => '1',
    'LENGTHTOKEN' => '40',
    'NO' => '1',
    'ZERO' => '0',
    'LIMIT' => '15',
    'LIMIT_RECORD' => '-4',
    'PAGE_PRODUCT_BUSINESS' =>6,
    'PAGE_PRODUCT_USER' =>12,
    'BLOCK_USER' => '4',
    'Product' => '0',
    'Promotion' => '1',
    'limit_product' => '16',
    'STR_LIMIT' => '50',
    'SELECT_ONE' => '1',
];